service: stock-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  stock:
    handler: index.handler
    environment:
      increase_ENDPOINT: "https://qqd31dx6mj.execute-api.ap-northeast-2.amazonaws.com/product/donut"
    events:
      - sqs: arn:aws:sqs:ap-northeast-2:775385743817:stock_queue


